"""Cálculo de custo/markup alinhado ao Analise_Cotacao (db.py).

Cotação: PR_DESENHO.VLRCONJUNTO ou MT_MATERIALCOMP.VLRCOMPRAULTIMA
Pedido:  regra CKFABRICADO + VLRCUSTO + VLRCOMPRAULTIMA
"""

# JOINs reutilizáveis (alias oi = orçamento item, i = pedido item)
JOIN_CUSTO_ORCAMENTO = """
    LEFT JOIN PR_DESENHO D_ORC ON D_ORC.MATERIAL = oi.MATERIAL
    OUTER APPLY (
        SELECT TOP 1 MC.VLRCOMPRAULTIMA
        FROM MT_MATERIALCOMP MC
        WHERE MC.MATERIAL = oi.MATERIAL
        ORDER BY MC.VLRCOMPRAULTIMA DESC
    ) MC_ORC
"""

JOIN_CUSTO_PEDIDO = """
    LEFT JOIN PR_DESENHO D_PED ON D_PED.MATERIAL = i.MATERIAL
    OUTER APPLY (
        SELECT TOP 1 MC.VLRCOMPRAULTIMA
        FROM MT_MATERIALCOMP MC
        WHERE MC.MATERIAL = i.MATERIAL
        ORDER BY MC.VLRCOMPRAULTIMA DESC
    ) MC_PED
"""

CUSTO_UNITARIO_ORCAMENTO = """
    CASE
        WHEN ISNULL(D_ORC.VLRCONJUNTO, 0) > 0 THEN D_ORC.VLRCONJUNTO
        ELSE MC_ORC.VLRCOMPRAULTIMA
    END
"""

CUSTO_UNITARIO_PEDIDO = """
    CASE
        WHEN D_PED.CKFABRICADO = 1 THEN D_PED.VLRCONJUNTO
        WHEN D_PED.CKFABRICADO = 2 THEN MC_PED.VLRCOMPRAULTIMA
        ELSE ISNULL(NULLIF(i.VLRCUSTO, 0), MC_PED.VLRCOMPRAULTIMA)
    END
"""
